apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/msm17b019/argocd-new-test.git
              revision: main
              files:
              - path: config/environment/clusters/*/apps/*/config.json
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  argocd.argoproj.io/cluster-name: '{{path[3]}}'
  template:
    metadata:
      name: '{{path[3]}}-{{path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
      - chart: '{{chart.name}}'
        repoURL: '{{chart.repoUrl}}'
        targetRevision: '{{chart.version}}'
        helm:
          releaseName: 'test-{{path.basename}}'
          valueFiles:
          - $values/config/environment/clusters/{{path[3]}}/apps/{{path.basename}}/values.yaml
      - repoURL: https://github.com/msm17b019/argocd-new-test.git
        targetRevision: main
        ref: values
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true